### ISSUE TITLE
RFC: Finne ut om vi kan bruke HAR-APIene til Chrome for å hente nedlastet data

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/STAut-Chrome-Datasank#2]
Når en browser går inn på en event-side (altså, billettsalget for en kamp) hos TicketMaster, lastes setekart og setetilgjengelighet ned automatisk. Det er nedlastning av sistnevnte som er blokkert for tiden, og som gjør at vi må tenke nytt. Ihvertfall den delen av det som er verst.

Chrome har noen HAR-APIer som kan brukes for å analysere nettverkstrafikk under en sidelasting. Kan vi også få ut content via den? Isåfall ser det ut som det kan være nøkkelen til få ned data.

Hvis ikke, ser det ut til at vi må gjøre ting i to steg; Først gå inn på siden, så sende avgårde en separat request for å laste ned datafila. Dette virker i det minste om man gjør det manuelt med dev-verktøyene.

**Comment by havremunken** [comment]
Ting tider på at disse APIene kun er tilgjengelige dersom Chrome devtools (F12) er åpne. Og de kan man visstnok ikke åpne fra en extension uten å bruke experimental APIs, noe som diskvalifiserer den fra å dukke opp i Chrome store...

Dette er litt drøyt å forvente av bruker. Spørsmålet da er om vi bare må gå inn på siden, la den laste ferdig, og så starte vår egen download av availability-fila.

**Comment by larsjaas** [comment]
Syns det virker alt for ambisiøst å crowdsource innsankingen via en chrome extension.

Hva med å lage seg en liten http-proxy for ticketmaster, som kjenner igjen URLene til availability-filene, og så ha en desktop med browser stående og peke på ticketmaster via proxyen? Tror browseren henter ned oppdaterte data til stadighet så de requestene går jevnt og trutt så lenge du ser på Lerkendal stadion for en event. Proxyen identifiserer alle requests/responses som dreier deg om availability og dumper dem til disk for staut i tillegg til å fore browseren med dataene.

Når jeg tenker meg om vil kanskje https gjøre proxying vanskelig, men om man kunne force http så er en slik proxy triviell å implementere.

**Comment by havremunken** [comment]
Det er absolutt en god tanke det. Jeg har ikke sett på proxy-muligheter, men det stemmer at websiden til TM henter datafila på nytt hvert 60. sekund, så det burde gå an. Det finnes sikkert mer eller mindre ferdige proxy-implementasjoner man kan sette opp og hooke inn i også - f.eks. i NPM.

Med bruk av et sertifikat på proxy bør man også kunne dekode https (dette gjøres f.eks. i brannmurer for å kunne sjekke at det ikke er stygt innhold som hentes), men det kan godt være at dette er mer pes enn det er verdt.

Når det gjelder crowdsourcinga skal det ikke være mange som trengs for å få det til å gå rundt, selv har jeg noen PCer som er online 24/7, noen som er på så lenge jeg er våken, og det skjer sjeldent så mye spennende med billettsalg om natta. Får vi overtalt 1-2 til så er vi langt på vei. Men klart, hvis vi heller kan bruke en proxy som mellomledd er det en god sjanse for at det er mye mindre utviklingstid det er snakk om.

Skal sjekke proxy-prosjekter som kan brukes!

**Comment by havremunken** [comment]
Mulig kandidat som kan brukes: https://mitmproxy.org/

Fortsetter dette i egen RFC. :)

**Comment by havremunken** [comment]
Dette var altså ikke riktig vei å gå, dermed lukkes den.
